CREATE PROCEDURE SP_InsertUser
(
 @USERS_NAME VARCHAR (50) = ' ',
 @USER_PASSWORD VARCHAR (100) = ' ',
 @START_DATE DATE =' ',
 @WEEKS INT = 0
)
AS
BEGIN
 INSERT INTO USERS (USERS_NAME,[START_DATE],WEEKS,USER_PASSWORD)
 VALUES (@USERS_NAME,@START_DATE,@WEEKS,@USER_PASSWORD)
END