CREATE PROCEDURE SP_InsertPlannedList
(
@PLANNED_ID INT = 0,
@MODULES_ID VARCHAR(8) = ' ',
@HOURS INT = 0
)
AS
BEGIN
INSERT INTO PLANNED_LIST (PLANNED_ID,MODULES_ID,[HOURS])
VALUES (@PLANNED_ID,@MODULES_ID,@HOURS)
END

