CREATE PROCEDURE SP_InsertModuleList
(
 @MODULES_ID VARCHAR(8) = '',
 @USERS_NAME VARCHAR (50) = ' '
)
AS
BEGIN
INSERT INTO MODULES_LIST(MODULES_ID,USERS_NAME)
VALUES (@MODULES_ID,@USERS_NAME)
END