CREATE PROCEDURE SP_InsertModule
(
 @MODULES_ID VARCHAR(8) = '',
 @NAME VARCHAR(50)= '',
 @CREDITS INT = 0,
 @HOURS INT = 0
)
AS
BEGIN
INSERT INTO MODULES (MODULES_ID,[NAME],CREDITS,[HOURS])
 VALUES (@MODULES_ID,@NAME,@CREDITS,@HOURS)
END