CREATE PROCEDURE SP_Reset
AS
BEGIN
	DROP TABLE PLANNED_LIST;
	DROP TABLE DATES_LIST;
	DROP TABLE PLANNED;
	DROP TABLE STORED_DATES;
	DROP TABLE MODULES_LIST;
	DROP TABLE MODULES;
	DROP TABLE USERS;

CREATE TABLE USERS (
USERS_NAME VARCHAR (50) NOT NULL,
USER_PASSWORD VARCHAR (100) NOT NULL,
[START_DATE] DATE NOT NULL,
WEEKS INT NOT NULL,
PRIMARY KEY (USERS_NAME)
);
CREATE TABLE MODULES (
MODULES_ID VARCHAR(8) NOT NULL,
[NAME] VARCHAR(50) NOT NULL,
CREDITS INT NOT NULL,
[HOURS] INT NOT NULL,
PRIMARY KEY (MODULES_ID)
);

CREATE TABLE MODULES_LIST (
MODULES_ID VARCHAR(8) NOT NULL,
USERS_NAME VARCHAR (50) NOT NULL,
PRIMARY KEY (MODULES_ID,USERS_NAME),
FOREIGN KEY (MODULES_ID) REFERENCES MODULES (MODULES_ID),
FOREIGN KEY (USERS_NAME) REFERENCES USERS (USERS_NAME),
);

CREATE TABLE STORED_DATES (
STORED_DATE DATE NOT NULL,
PRIMARY KEY (STORED_DATE)
);

CREATE TABLE PLANNED (
PLANNED_ID INT NOT NULL,
PRIMARY KEY (PLANNED_ID )
);

CREATE TABLE DATES_LIST (
STORED_DATE DATE NOT NULL,
USERS_NAME VARCHAR (50) NOT NULL,
PLANNED_ID INT,
PRIMARY KEY (STORED_DATE,USERS_NAME),
FOREIGN KEY (STORED_DATE) REFERENCES STORED_DATES (STORED_DATE),
FOREIGN KEY (USERS_NAME) REFERENCES USERS (USERS_NAME),
FOREIGN KEY (PLANNED_ID ) REFERENCES PLANNED (PLANNED_ID ),
);

CREATE TABLE PLANNED_LIST (
PLANNED_ID INT,
MODULES_ID VARCHAR(8),
[HOURS] INT,
PRIMARY KEY (PLANNED_ID,MODULES_ID),
FOREIGN KEY (PLANNED_ID) REFERENCES PLANNED (PLANNED_ID),
FOREIGN KEY (MODULES_ID) REFERENCES MODULES (MODULES_ID),
);
END
